/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Anthony Bonasso
 */
public class CakeForm extends javax.swing.JFrame {

    /**
     * Creates new form CakeForm
     */
    public CakeForm() {
        modelOrders = new DefaultListModel<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpSizes = new javax.swing.ButtonGroup();
        jPanelOrderInfo = new javax.swing.JPanel();
        lblFName = new javax.swing.JLabel();
        txtfirstName = new javax.swing.JTextField();
        lblLName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblFlavor = new javax.swing.JLabel();
        cmbFlavors = new javax.swing.JComboBox<>();
        lblCakeSize = new javax.swing.JLabel();
        radSmall = new javax.swing.JRadioButton();
        radMed = new javax.swing.JRadioButton();
        radLrg = new javax.swing.JRadioButton();
        chkDelivery = new javax.swing.JCheckBox();
        jPanelAllOrders = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstOrders = new javax.swing.JList();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAbout = new javax.swing.JMenu();
        mnuItmVersion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cake Order App");

        jPanelOrderInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Order Information"));

        lblFName.setText("First Name:");

        txtfirstName.setToolTipText("");

        lblLName.setText("Last Name:");

        txtLastName.setToolTipText("");

        lblPhoneNumber.setText("Phone Number:");

        txtPhone.setToolTipText("");

        lblFlavor.setText("Cake Flavor:");

        cmbFlavors.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "APPLE", "CARROT", "CHEESECAKE", "CHOCOLATE", "COFFEE", "OPERA", "TIRAMISU" }));

        lblCakeSize.setText("Cake Size:");

        btnGrpSizes.add(radSmall);
        radSmall.setSelected(true);
        radSmall.setText("Small");
        radSmall.setActionCommand("SMALL");

        btnGrpSizes.add(radMed);
        radMed.setText("Medium");
        radMed.setActionCommand("MEDIUM");

        btnGrpSizes.add(radLrg);
        radLrg.setText("Large");
        radLrg.setActionCommand("LARGE");

        chkDelivery.setText("Free Delivery");
        chkDelivery.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanelOrderInfoLayout = new javax.swing.GroupLayout(jPanelOrderInfo);
        jPanelOrderInfo.setLayout(jPanelOrderInfoLayout);
        jPanelOrderInfoLayout.setHorizontalGroup(
            jPanelOrderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrderInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOrderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOrderInfoLayout.createSequentialGroup()
                        .addGroup(jPanelOrderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFName, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelOrderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtfirstName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addGroup(jPanelOrderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFlavor, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(lblLName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanelOrderInfoLayout.createSequentialGroup()
                        .addComponent(lblCakeSize, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radSmall)
                        .addGap(18, 18, 18)
                        .addComponent(radMed)
                        .addGap(18, 18, 18)
                        .addComponent(radLrg)
                        .addGap(106, 106, 106)))
                .addGroup(jPanelOrderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkDelivery)
                    .addComponent(txtLastName)
                    .addComponent(cmbFlavors, 0, 120, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanelOrderInfoLayout.setVerticalGroup(
            jPanelOrderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrderInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOrderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelOrderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFlavor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFlavors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelOrderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCakeSize, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radSmall)
                    .addComponent(radMed)
                    .addComponent(radLrg)
                    .addComponent(chkDelivery))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblFName.getAccessibleContext().setAccessibleDescription("");

        jPanelAllOrders.setBorder(javax.swing.BorderFactory.createTitledBorder("Current Orders"));

        lstOrders.setModel(modelOrders);
        jScrollPane1.setViewportView(lstOrders);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAllOrdersLayout = new javax.swing.GroupLayout(jPanelAllOrders);
        jPanelAllOrders.setLayout(jPanelAllOrdersLayout);
        jPanelAllOrdersLayout.setHorizontalGroup(
            jPanelAllOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAllOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAllOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAllOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanelAllOrdersLayout.setVerticalGroup(
            jPanelAllOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAllOrdersLayout.createSequentialGroup()
                .addGroup(jPanelAllOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAllOrdersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemove)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrint)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuit)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        mnuAbout.setText("About");

        mnuItmVersion.setText("Version");
        mnuItmVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmVersionActionPerformed(evt);
            }
        });
        mnuAbout.add(mnuItmVersion);

        jMenuBar1.add(mnuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelAllOrders, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelOrderInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanelOrderInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelAllOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtfirstName.getText().isEmpty() || txtLastName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please dont Leave any feilds Blank", "Missing Information", JOptionPane.ERROR_MESSAGE);
        }
        try {
            Order order = new Order(txtfirstName.getText(), txtLastName.getText(), Long.parseLong(txtPhone.getText()),
                    chkDelivery.isSelected(), CakeFlavors.valueOf(cmbFlavors.getSelectedItem().toString()), CakeSize.valueOf(btnGrpSizes.getSelection().getActionCommand()));

            //search for Order
            boolean foundO = false;
            for (int i = 0; i < modelOrders.size(); i++) {
                if (modelOrders.getElementAt(i).getPhone() == order.getPhone()) {
                    modelOrders.setElementAt(order, i);
                    foundO = true;
                    break;
                }
            }
            if (!foundO) {
                modelOrders.addElement(order);
            }
            ResetForm();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please only enter a valid Phone Number", "Invalid Phone", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (lstOrders.getSelectedIndex() > -1) {
            Order ord = modelOrders.getElementAt(lstOrders.getSelectedIndex());
            txtfirstName.setText(ord.getfName());
            txtLastName.setText(ord.getlName());
            txtPhone.setText(Long.toString(ord.getPhone()));
            chkDelivery.setSelected(ord.isDelivery());
            cmbFlavors.setSelectedItem(ord.getFlavor().toString());

            Enumeration<AbstractButton> btns = btnGrpSizes.getElements();
            while (btns.hasMoreElements()) {
                AbstractButton button = btns.nextElement();
                if (button.getActionCommand().equals(ord.getSize().toString())) {
                    button.setSelected(true);
                    break;
                }
            }
        }

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
       if(lstOrders.getSelectedIndex() > -1){
           modelOrders.removeElementAt(lstOrders.getSelectedIndex());
       }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        
        int result = JOptionPane.showConfirmDialog(null, "Would you Like to save current list?", "Save current list", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            try (BufferedWriter out = new BufferedWriter(new FileWriter("Orders.txt"))) {
                for (int i = 0; i < modelOrders.size(); i++) {
                    out.write(modelOrders.getElementAt(i).toString());
                    out.newLine();

                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error Printing", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        if (!modelOrders.isEmpty()) {
            int result = JOptionPane.showConfirmDialog(null, "Would you Like to save current list Before Quitting?", "Save Before Quit", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                try (BufferedWriter out = new BufferedWriter(new FileWriter("Orders.txt"))) {
                    for (int i = 0; i < modelOrders.size(); i++) {
                        out.write(modelOrders.getElementAt(i).toString());
                        out.newLine();

                    }
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Error Printing", JOptionPane.ERROR_MESSAGE);

                }

            }
         if(result == JOptionPane.NO_OPTION){
             super.dispose();
         }
        }else{
            super.dispose();
        }

    }//GEN-LAST:event_btnQuitActionPerformed

    private void mnuItmVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmVersionActionPerformed
       JOptionPane.showMessageDialog(null,"Cake App Vers: 1.0.0","Version Check",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnuItmVersionActionPerformed
    private void ResetForm(){
        txtfirstName.setText("");
        txtLastName.setText("");
        txtPhone.setText("");
        cmbFlavors.setSelectedIndex(0);
        chkDelivery.setSelected(false);
        radSmall.setSelected(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CakeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CakeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CakeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CakeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CakeForm().setVisible(true);
            }
        });
    }
    private DefaultListModel<Order> modelOrders;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.ButtonGroup btnGrpSizes;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkDelivery;
    private javax.swing.JComboBox<String> cmbFlavors;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelAllOrders;
    private javax.swing.JPanel jPanelOrderInfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCakeSize;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblFlavor;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JList lstOrders;
    private javax.swing.JMenu mnuAbout;
    private javax.swing.JMenuItem mnuItmVersion;
    private javax.swing.JRadioButton radLrg;
    private javax.swing.JRadioButton radMed;
    private javax.swing.JRadioButton radSmall;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtfirstName;
    // End of variables declaration//GEN-END:variables
}
